{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.2",
    "title": "Kapu$ta docs",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "http://localhost:3030/api" },
    { "url": "https://kapusta-dvde.onrender.com/api" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Transactions",
      "description": "Transactions endpoints"
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "email": "user@gmail.com",
                  "password": "12345678"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "user@gmail.com"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "email": "user@gmail.com",
                  "password": "12345678"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "user@gmail.com",
                    "balance": "123",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjY3Zjk1ZmJhNjRiNGRkZGVmOTNjZSIsImlhdCI6MTY3NzEzNzY0MSwiZXhwIjoxNjc3MTczNjQxfQ.Oz4jji9rKghQqZMDEEw97eiYqAvjSBoT09Gn7-REZsM"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "description": "message",
                  "example": "No content"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/auth/users/balance": {
      "patch": {
        "tags": ["Auth"],
        "security": [{ "Bearer": [] }],
        "summary": "receiving the user's balance",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "balance": "777"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "newUserBalance": "777"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      },
      "get": {
        "tags": ["Auth"],
        "security": [{ "Bearer": [] }],
        "summary": "updating the user's balance",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "balance": "777"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/auth/users/current": {
      "get": {
        "tags": ["Auth"],
        "security": [{ "Bearer": [] }],
        "summary": "receiving a user",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "user@gmail.com",
                    "balance": "777",
                    "token": "123exampleToken"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/auth/google": {
      "get": {
        "tags": ["Auth"],
        "summary": "User login by google",
        "responses": {
          "200": {
            "description": "URl string with query params",
            "content": {
              "url": {
                "example": "http://example.com/api?email=email&token=token&balance=balance"
              }
            }
          },
          "401": {
            "description": "google authorization error"
          }
        }
      }
    },
    "/transactions": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get all user transactions",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "userId": "111111111111111111111111",
                      "_id": "22222222222222",
                      "dateTransaction": "2020-03-22T21:21:41.052+00:00",
                      "income": false,
                      "sum": "120",
                      "category": "description",
                      "description": "shirt"
                    },
                    {
                      "userId": "111111111111111111111111",
                      "_id": "22222222222222",
                      "dateTransaction": "2020-03-22T21:21:41.052+00:00",
                      "income": false,
                      "sum": "120",
                      "category": "description",
                      "description": "shirt"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "No users found"
          }
        }
      }
    },
    "/transactions/expenses": {
      "post": {
        "tags": ["Transactions"],
        "summary": "Add expenses transaction",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "dateTransaction": "2020-03-22T21:21:41.052+00:00",
                  "income": false,
                  "sum": "120",
                  "category": "description",
                  "description": "shirt"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "userId": "111111111111111111111111",
                    "_id": "22222222222222",
                    "dateTransaction": "2020-03-22T21:21:41.052+00:00",
                    "income": false,
                    "sum": "120",
                    "category": "description",
                    "description": "shirt"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/transactions/income": {
      "post": {
        "tags": ["Transactions"],
        "summary": "Add income transaction",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "dateTransaction": "2020-03-22T21:21:41.052+00:00",
                  "income": true,
                  "sum": "120",
                  "category": "description",
                  "description": "shirt"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "userId": "111111111111111111111111",
                    "_id": "22222222222222",
                    "dateTransaction": "2020-03-22T21:21:41.052+00:00",
                    "income": true,
                    "sum": "120",
                    "category": "description",
                    "description": "shirt"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/transactions/:transactionId": {
      "delete": {
        "tags": ["Transactions"],
        "summary": "delete transaction",
        "parameters": [{ "in": "path", "name": "transactionId" }],
        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "description": "message",
                  "example": {
                    "message": "The transaction is successfully deleted!",
                    "userId": "111111111111111111111111"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/transactions/incomeMonths": {
      "post": {
        "tags": ["Transactions"],
        "summary": "receiving income for the month",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "year": "2023",
                  "currentMonth": "2",
                  "userId": "63f09d03f2f85fb05e29c4as"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "total": 2000,
                      "month": 1
                    },
                    {
                      "total": 10000,
                      "month": 2
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/transactions/expensesMonths": {
      "post": {
        "tags": ["Transactions"],
        "summary": "receiving expenses for the month",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "year": "2023",
                  "currentMonth": "2",
                  "userId": "63f09d03f2f85fb05e29c4as"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "total": 2000,
                      "month": 1
                    },
                    {
                      "total": 10000,
                      "month": 2
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    },
    "/transactions/fullStatistics": {
      "post": {
        "tags": ["Transactions"],
        "summary": "receiving all statistics for the month",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "year": "2023",
                  "currentMonth": "10"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "parameters": [],
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "icome": {
                      "totalSum": 1800,
                      "categories": [
                        {
                          "category": "Clothes",
                          "sum": 1300,
                          "descriptions": [
                            {
                              "description": "bed",
                              "sum": 500
                            },
                            {
                              "description": "bed2",
                              "sum": 500
                            },
                            {
                              "description": "shirt",
                              "sum": 300
                            }
                          ]
                        },
                        {
                          "category": "Food",
                          "sum": 500,
                          "descriptions": [
                            {
                              "description": "jjhhhgg",
                              "sum": 500
                            }
                          ]
                        }
                      ]
                    },
                    "expenses": {
                      "totalSum": 4500,
                      "categories": [
                        {
                          "category": "HomeSpace",
                          "sum": 800,
                          "descriptions": [
                            {
                              "description": "jjhhhgg",
                              "sum": 800
                            }
                          ]
                        },
                        {
                          "category": "Furniture",
                          "sum": 300,
                          "descriptions": [
                            {
                              "description": "sofa",
                              "sum": 300
                            }
                          ]
                        },
                        {
                          "category": "Home",
                          "sum": 1800,
                          "descriptions": [
                            {
                              "description": "new",
                              "sum": 500
                            },
                            {
                              "description": "tyre",
                              "sum": 1300
                            }
                          ]
                        },
                        {
                          "category": "Clothes",
                          "sum": 1600,
                          "descriptions": [
                            {
                              "description": "Homdh",
                              "sum": 650
                            },
                            {
                              "description": "wow",
                              "sum": 950
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Provided email already exists"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
